= Prerequisites

In order to start the whole exercise from the `{oai}` perspective, we will need to deploy and configure some applications which will be used later on:

== MinIO

The model we want to train and use later on needs to reside somewhere. `{oai}` has a featue which is called `Data Connection` where we can reference storage used for serving our model later on. This storage needs to be an S3 bucket, therefore we will make use of `MinIO` which enables us to create such buckets in our cluster.

To install `MinIO`:

. Create a `namespace`, for example `minio-{your-name}`
+
[source,bash,role=execute]
----
oc new-project minio-{your-name}
----
.. This command will also set your current project scope to be this one. If you created the namespace via the `{ocpc}` (UI), you have to set the project manually.
+
[source,bash,role=execute]
----
oc project minio-{your-name}
----
. Deploy the manifests for `MinIO`
+
[source,yaml,role=execute]
----
oc apply -f https://raw.githubusercontent.com/sa-mw-dach/windy-journey/main/manifests/infra/05-minio/minio.yaml
----
.. Feel free to check the resources which are being generated by opening the link in the browser. There you can see `PersistentVolumeClaim`, `Secret`, `Deployment` and two `Route` objects being created.
+
NOTE: The login ceredentials for your `MinIO` instance can be seen there in the `Secret`, it's `minio` with `minio123`.