= Prerequisites

In order to start the whole exercise from the `{ocpai}` perspective, we will need to deploy and configure some applications and resources which will be used later on:

== Project

A project is a Kubernetes namespace with additional annotations, and is the central vehicle by which access to resources for regular users is managed. A project allows a team of users to organize and manage their content in isolation from other teams, therefore making multi tenancy more straight forward.

Ultimately, you will deploy applications and resources in namespaces. So lets create your namespace for this workshop!

Head over to the {ocp} console to create your projet.

On the top left corner 


== MinIO

The model we want to train and use later on needs to reside somewhere. `{ocpai}` has a featue which is called `Data Connection` where we can reference storage used for serving our model later on. This storage needs to be an S3 bucket, therefore we will make use of `MinIO` which enables us to create such buckets in our cluster.

To install `MinIO`:

. Create a `namespace`, for example `minio-{your-name}`
+
[source,bash,role=execute]
----
oc new-project minio-{your-name}
----
.. This command will also set your current project scope to be this one. If you created the namespace via the `{ocpc}` (UI), you have to set the project manually.
+
[source,bash,role=execute]
----
oc project minio-{your-name}
----
. Deploy the manifests for `MinIO`
+
[source,yaml,role=execute]
----
oc apply -f https://raw.githubusercontent.com/sa-mw-dach/windy-journey/main/manifests/infra/05-minio/minio.yaml
----
.. Feel free to check the resources which are being generated by opening the link in the browser. There you can see `PersistentVolumeClaim`, `Secret`, `Deployment` and two `Route` objects being created.
+
NOTE: The login credentials for your `MinIO` instance can be seen there in the `Secret`, it's `minio` with `minio123`.